version: "3"

services:

  server:
    image: neoontology-server
    build:
      context: ./server
    volumes:
      - ./assets:/server/assets
    ports:
      - "3003:3003"

  store:
    container_name: neoontologydocker_store_1
    image: neo4j:3.5
    depends_on:
      - server
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "n10s"]
      - NEO4J_AUTH=neo4j/opexcellence